### ISSUE TITLE
Right hand annotation UI not displaying 

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#16]
(submitted in Jira as ANNO-58) 

It appears that the characters in the are not being escaped properly in the user entered citation field.

Leah Reis-Dennis is an instructor in the Annotation Test - English site.   She uploaded a poem called the filling station.   Although the poem displayed, the annotation UI that should appear on the right side of the screen does not appear.  Artie's initial investigation indicated it may be that in the citation field, quotation marks aren't being escaped/normalized - he's looking in to this.

![screen shot 2015-09-03 at 10 51 28 am](https://cloud.githubusercontent.com/assets/2422354/9661683/cc1b7950-5229-11e5-800f-876be07754e9.png)

**Comment by arthurian** [comment]
@ShannonRice This issue is fixed by https://github.com/Harvard-ATG/annotationsx/pull/18 and I've deployed the fix to P-1, so the issue should be fixed on the [English Annotation Test Site](canvas.harvard.edu/courses/7145). I plan to contribute the bug fix upstream to @lduarte1991 as soon as https://github.com/lduarte1991/hx-annotations-lti/pull/4 is merged.

**Comment by lduarte1991** [comment]
Yup, working on #4 today!

**Comment by arthurian** [comment]
Awesome, thanks!

**Comment by lduarte1991** [comment]
@arthurian if you could make [#18](https://github.com/Harvard-ATG/annotationsx/pull/18) a PR against lduarte1991:master that would be fantastic as well and I could merge it immediately as it only touches that one html file.

**Comment by arthurian** [comment]
@lduarte1991 I can't submit #18 to lduarte1991:master as it currently stands, since it would come with all the history of our residential branch, which you probably don't want. Instead, I'm going to sync harvard-atg:master with lduarte1991:master, cherry-pick this commit and apply it to master, and then submit a PR from master to master, that way you just get the isolated bug fix.
