### ISSUE TITLE
unable to make annotation on assignment with non-ascii text 

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/annotationsx#46]
(using chrome)
https://canvas.harvard.edu/courses/7145/external_tools/9703

I set up an assignment in non-ascii characters. (I happened to use Japanese.)  

when I go to the assignment, select text, and attempt to submit an annotation, I get an error that says, "Sorry, we could not create this Annotation".  

The anntoation seems to be in the database, as it is visible if I move my mouse over the highlighted text, but it doesn't display in the panel on the right hand side.

**Comment by arthurian** [comment]
Found the issue - the DEV database character encoding wasn't updated from latin1 to utf8 when this issue came up before. I guess we just fixed production and forgot to go back and fix development. Working on fixing that now.

**Comment by arthurian** [comment]
@ShannonRice This should be resolved now. Ethan helped me update the character encoding on the DEV database so non-ascii characters should work now. Just tested it out with Japanese and it saved successfully.

Closing this issue since it should be resolved. Feel free to re-open if you find otherwise.
